- name: bug
  description: "An issue related to a bug or unexpected behavior."
  color: "d73a4a"
- name: enhancement
  description: "A new feature or an improvement to an existing feature."
  color: "a2eeef"
- name: question
  description: "A question about the project or its usage."
  color: "d876e3"
- name: support
  description: "Request for assistance or support."
  color: "0e8a16"
- name: documentation
  description: "Improvements or additions to documentation."
  color: "c5def5"
- name: improvement
  description: "A general improvement to the project."
  color: "0075ca"
- name: translation
  description: "Request or contribution for translating content."
  color: "f29513"
- name: localization
  description: "Issues or tasks related to localizing the project."
  color: "c27803"
- name: content
  description: "Issues related to content creation or updates."
  color: "1d7f77"
- name: new-source
  description: "Suggestion or addition of a new data source."
  color: "006b75"
- name: website
  description: "Issues or tasks related to the project website."
  color: "0052cc"
- name: youtube
  description: "Issues or tasks related to YouTube content or integration."
  color: "ff0000"
- name: "priority: critical"
  description: "Critical priority: requires immediate attention."
  color: "b60205"
- name: "priority: high"
  description: "High priority: should be addressed soon."
  color: "d93f0b"
- name: "priority: medium"
  description: "Medium priority: should be addressed in due course."
  color: "fbca04"
- name: "priority: low"
  description: "Low priority: can be addressed when time permits."
  color: "c2e0c6"
- name: "status: confirmed"
  description: "The issue or task has been confirmed."
  color: "1d76db"
- name: "status: in progress"
  description: "Work on this issue or task is currently in progress."
  color: "fca321"
- name: "status: needs review"
  description: "This issue or task needs review from maintainers."
  color: "bf87ff"
- name: "status: blocked"
  description: "Progress on this issue or task is currently blocked."
  color: "535353"
- name: "status: completed"
  description: "This issue or task has been completed."
  color: "1E8E3E"
- name: "type: chore"
  description: "Routine tasks, maintenance, or non-functional changes."
  color: "f0f0f0"
- name: "type: refactor"
  description: "Code refactoring without changing external behavior."
  color: "f9d0c4"
- name: "type: test"
  description: "Adding missing tests or improving existing ones."
  color: "76dbbe"
- name: "good first issue"
  description: "A good issue for first-time contributors."
  color: "7057ff"
- name: "help wanted"
  description: "Extra attention is needed for this issue or task."
  color: "008672"
- name: wontfix
  description: "This issue will not be fixed."
  color: "ededed"
- name: duplicate
  description: "This issue or pull request already exists."
  color: "cccccc"
- name: invalid
  description: "This issue or pull request is not valid."
  color: "e4e669"
